/**
 *class: BobbaTea
 *version:1.0
 *author: Shaikh Hasan
 *written: August 29, 2022,
 *description of this program: This program will generate an output of the cost of a Bobba tea cup.
 */
public class BobbaTea{
    public static void main (String [] args){
        int tea = 6;
        int tips = 2;
        double total = tea + tips;
        System.out.println(" The total cost of a cup is " + total + " dollars." );
    }
}
