/**
 *class: MyPetFish
 *version:1.0
 *author: Shaikh Hasan
 *written: August 29, 2022,
 *description of this program: This program will generate an output of sentences about the pet fish I have in my house.
 */
public class MyPetFish{
        public static void main (String [] args){
            int result= (Galaxy); //incorrect - syntax error
            System.out.println("The name of my Betta fish is " + result );
        }
}
